//
// Created by chenhao on 1/6/21.
//

#ifndef AVSAMPLES_MSG_DEF_H
#define AVSAMPLES_MSG_DEF_H


#define MSG_FLUSH 0

#define MSG_ERROR    100
#define MSG_PREPARED 101
#define MSG_COMPLETE 102
#define MSG_VIDEO_SIZE_CHANGED  103
#define MSG_RENDER_FIRST_FRAME  104
#define MSG_PLAYER_STATE_CHANGED 105
#define MSG_SEEK_COMPLETE 106
#define MSG_PLAYER_POSITION_CHANGED 107

#endif //AVSAMPLES_MSG_DEF_H
